version: '3'

services:
  database:
    container_name: translatecard-api-db
    hostname: translatecard-api-postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database