name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm test